dockerfile = "Dockerfile"

[identity]
name = "The Architect"

[env.CLAUDE_CODE_NO_FLICKER]
default = "1"

[claude]
plugins = [
  "superpowers@claude-plugins-official",
  "code-review@claude-plugins-official",
  "code-simplifier@claude-plugins-official",
  "feature-dev@claude-plugins-official",
  "commit-commands@claude-plugins-official",
  "github@claude-plugins-official",
  "ralph-loop@claude-plugins-official",
  "claude-md-management@claude-plugins-official",
  "skill-creator@claude-plugins-official",
  "security-guidance@claude-plugins-official",
  "claude-code-setup@claude-plugins-official",
  "pr-review-toolkit@claude-plugins-official",
  "explanatory-output-style@claude-plugins-official",
  "plugin-dev@claude-plugins-official",
  "hookify@claude-plugins-official",
  "learning-output-style@claude-plugins-official",
  "rust-analyzer-lsp@claude-plugins-official",
  "jackin-dev@jackin-marketplace",
]

[[claude.marketplaces]]
source = "jackin-project/jackin-marketplace"
