# SPDX-FileCopyrightText: 2026 Alexey Zhokhov
# SPDX-License-Identifier: Apache-2.0

[tools]
actionlint = "1.7.12"
gitleaks = "8.30.1"
prek = "0.4.12"
python = "3.14.7"
uv = "0.12.3"
"pipx:reuse" = { version = "6.2.0", extras = "charset-normalizer", depends = ["python"] }

[settings]
lockfile = true
