name: Publish Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    uses: jackin-project/jackin-role-action/.github/workflows/publish.yml@683eb05c8d8ab555c3bb2a1d3923871f2daeb5d7 # latest
    permissions:
      contents: read
      id-token: write
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
      github-readonly-token: ${{ secrets.GH_READONLY_TOKEN }}
