name: Publish Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    uses: jackin-project/jackin-role-action/.github/workflows/publish.yml@918e0958a2f695087b8e262ed90d3ed7c09c787a # latest
    permissions:
      contents: read
      id-token: write
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
      github-readonly-token: ${{ secrets.GH_READONLY_TOKEN }}
